# Site settings
title: Taco Destroyer
email: 
description: > # this means to ignore newlines until "baseurl:"
 I still love technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://sheagcraig.github.io" # the base hostname & protocol for your site
twitter_username: shea_craig
github_username:  sheagcraig

# Build settings
markdown: kramdown
